### ISSUE TITLE
Can't launch the application for development

### ISSUE THREAD

**Issue by DamienCassou** [cozy/cozy-banks#638]
I would like to try out working on cozy-banks source code but I fail to start the application.

# With yarn watch:browser

```
$ yarn watch:browser
...
ℹ ｢wds｣: Project is running at http://localhost:8282/
...
WARNING in react-is
  Multiple versions of react-is found:
...
ℹ ｢wdm｣: Compiled with warnings.
```

In http://localhost:8282/, I get many errors in the console and a blank page:

![2018-12-12-203209_955x479_scrot](https://user-images.githubusercontent.com/217543/49893973-0a16bf80-fe4d-11e8-92f9-984100e27b8b.png)

# With cozy-scripts start

```
$ npx cozy-scripts start --hot --browser
...
App successfully compiled!
  Your application:    http://banks.cozy.tools:8080
  Your local Cozy:     http://cozy.tools:8080
  CouchDB:             http://localhost:5984/_utils
  MailHog:             http://localhost:8025
  Dev assets:          http://localhost:8888
...
ERROR in multi webpack-dev-server/client?http://localhost:8888/ webpack/hot/dev-server /home/c
assou/.npm/_npx/6860/lib/node_modules/cozy-scripts/node_modules/babel-polyfill/lib/index.js /h
ome/cassou/.npm/_npx/6860/lib/node_modules/cozy-scripts/utils/reactExposer.js ./src/targets/br
owser/index.jsx                                                                              
Module not found: Error: Can't resolve '~/projects/cozy-banks/src/targets
/browser/index.jsx' in '~/projects/cozy-banks'                          
 @ multi webpack-dev-server/client?http://localhost:8888/ webpack/hot/dev-server /home/cassou/
.npm/_npx/6860/lib/node_modules/cozy-scripts/node_modules/babel-polyfill/lib/index.js /home/ca
ssou/.npm/_npx/6860/lib/node_modules/cozy-scripts/utils/reactExposer.js ./src/targets/browser/
index.jsx app[4]                                                                             

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve '~/projects/cozy-banks/src
  /targets/browser/index.ejs' in '~/projects/cozy-banks':               
  Error: Can't resolve '~/projects/cozy-banks/src/targets/browser/index.e
  js' in '~/projects/cozy-banks'                                        
```

**Comment by ptbrowne** [comment]
Sorry for the delay, @DamienCassou . It's great that you tried to start the application and I am sorry that the process was not smoother for you.

1) `http://localhost:8282` is the development server from webpack and it is not used to serve the HTML files. Otherwise, the variables filled by the server in the template are not filled (see https://github.com/cozy/cozy-banks/blob/master/src/index.ejs#L30). This webpack server is only used to serve the JS files (and have hot reload). To access the application, pass by the stack to serve the file index : go to the URL http://banks.cozy.tools:8080/.

To start the stack and tell it that it should serve the application banks from the current directory, the easiest way is to use our development docker image (this is done automatically via cozy-scripts but banks does not use it):

```
docker run --rm -p 8080:8080 -p 5984:5984 -p 8025:8025 -p /BANKS/DIRECTORY/build:/data/cozy-app/banks cozy/cozy-app-dev
```

`/BANK/DIRECTORY` should be replaced.

A CouchDB server is also started in the Docker process. 

2) `cozy-scripts` is not used to start cozy-banks. We should use `cozy-scripts` in cozy-banks but we did not take the time to integrate it yet.

Do not hesitate if you have any other questions, and sorry again for the troubles you experienced.

**Comment by DamienCassou** [comment]
I think you mean `-v` instead of `-p` before `/BANKS/DIRECTORY`

**Comment by kosssi** [comment]
@DamienCassou it's ok you succeed?

**Comment by DamienCassou** [comment]
@kosssi yes I did. But, in my opinion, there is work to do:

1. fix the README
2. add something to disable CSP (as in https://github.com/CPatchane/create-cozy-app/blob/master/packages/cozy-scripts/scripts/start.js#L174)

**Comment by ptbrowne** [comment]
Can  you tell me if https://github.com/cozy/cozy-banks/pull/712/files makes the README clearer ?

**Comment by DamienCassou** [comment]
Patrick Browne <notifications@github.com> writes:
> Can  you tell me if https://github.com/cozy/cozy-banks/pull/712/files makes the README clearer ?


it's much better, thank you. The paragraph about the CSP is good and I
would add a link to a browser extension and a sentence about how and
where to change the configuration.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by ptbrowne** [comment]
Thanks, I did [the changes](https://github.com/cozy/cozy-banks/pull/712). I am closing this. Feel free to reopen if you still have problems.

**Comment by DamienCassou** [comment]
Thank you very much.
